/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import bean.Presupuesto;
import bean.Reserva;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorge
 */
public class BuscarPresupuesto extends javax.swing.JFrame {
    private char ch;
    private int fila;
    private int numero;
    private String estado;
    private String fechaEmision;
    private String cedula;
    Date fecha= new Date();
      DateFormat formato=new SimpleDateFormat("dd-MM-yyyy");
    /**
     * Creates new form BuscarPresupuesto
     */
    public BuscarPresupuesto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("proyectoPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Presupuesto p");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        jScrollPane2 = new javax.swing.JScrollPane();
        masterTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        list_filtros = new javax.swing.JComboBox();
        lbl_filtro = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        tf_valor = new javax.swing.JTextField();
        lbl_valor = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JButton();
        panel_auditoria = new javax.swing.JPanel();
        lbl_auditoria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, masterTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${numPresupuesto}"));
        columnBinding.setColumnName("Numero Presupuesto");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ciCliente}"));
        columnBinding.setColumnName("Cedula Cliente");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${estado}"));
        columnBinding.setColumnName("Estado");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fechaEmision}"));
        columnBinding.setColumnName("Fecha Emision");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        masterTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masterTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(masterTable);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        list_filtros.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Numero Presupuesto", "Estado", "Fecha Emisión", "Cedula" }));
        list_filtros.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                list_filtrosFocusLost(evt);
            }
        });

        lbl_filtro.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lbl_filtro.setText("Buscar por:");

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zoom.png"))); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        btn_buscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btn_buscarFocusLost(evt);
            }
        });

        tf_valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_valorKeyTyped(evt);
            }
        });

        lbl_valor.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        lbl_valor.setText("Valor:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbl_filtro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(list_filtros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lbl_valor)
                .addGap(18, 18, 18)
                .addComponent(tf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_buscar)
                    .addComponent(tf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_valor)
                    .addComponent(list_filtros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_filtro))
                .addContainerGap())
        );

        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete.png"))); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        panel_auditoria.setBackground(new java.awt.Color(0, 153, 255));
        panel_auditoria.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lbl_auditoria.setFont(new java.awt.Font("Corbel", 1, 30)); // NOI18N
        lbl_auditoria.setForeground(new java.awt.Color(255, 255, 255));
        lbl_auditoria.setText("Buscar Presupuesto");

        javax.swing.GroupLayout panel_auditoriaLayout = new javax.swing.GroupLayout(panel_auditoria);
        panel_auditoria.setLayout(panel_auditoriaLayout);
        panel_auditoriaLayout.setHorizontalGroup(
            panel_auditoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_auditoriaLayout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(lbl_auditoria)
                .addGap(138, 138, 138))
        );
        panel_auditoriaLayout.setVerticalGroup(
            panel_auditoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_auditoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_auditoria)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(panel_auditoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cancelar)
                .addGap(251, 251, 251))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panel_auditoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btn_cancelar)
                .addGap(19, 19, 19))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void list_filtrosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_list_filtrosFocusLost
        // TODO add your handling code here:
        if(list_filtros.getSelectedItem()=="Fecha Emisión"){
          
            tf_valor.setText(formato.format(fecha));
        }

    }//GEN-LAST:event_list_filtrosFocusLost

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
        String opcion;
        if (tf_valor.getText().length()==0){
            JOptionPane.showMessageDialog(null,"Ingrese algún valor para efectuar la búsqueda", "Advertencia",JOptionPane.ERROR_MESSAGE);
            return;
        }else{
            opcion=(String) list_filtros.getSelectedItem();
            if(opcion.equals("Numero Presupuesto")){
                query=entityManager.createNamedQuery("Presupuesto.findByNumPresupuesto");
                query.setParameter("numPresupuesto", Integer.parseInt(tf_valor.getText()));
                List<Presupuesto> p=query.getResultList();
                if(p.isEmpty()){
                    JOptionPane.showMessageDialog(null,"Número de Presupuesto Inexistente", "Error",JOptionPane.ERROR_MESSAGE);
                    tf_valor.setText(null);
                    return;
                }
                list.clear();
                list.addAll(p);
                return;
            }else if(opcion.equals("Estado")){
                query=entityManager.createNativeQuery("SELECT * FROM presupuesto WHERE estado LIKE "
                    +"'%"+tf_valor.getText()+"%'", Presupuesto.class);
                List<Presupuesto> p=query.getResultList();
                if(p.isEmpty()){
                    JOptionPane.showMessageDialog(null,"No se han encontrado registros para dicho estado", "Error",JOptionPane.ERROR_MESSAGE);
                    tf_valor.setText(null);
                    return;
                }
                list.clear();
                list.addAll(p);
                return;

            }else if(opcion.equals("Fecha Emisión")){
                query=entityManager.createNamedQuery("Presupuesto.findByFechaEmision");
                query.setParameter("fechaEmision",tf_valor.getText() );
                List<Presupuesto> p=query.getResultList();
                if(p.isEmpty()){
                    JOptionPane.showMessageDialog(null,"No se han encontrado registros para dicha fecha", "Error",JOptionPane.ERROR_MESSAGE);
                    tf_valor.setText(null);
                    return;
                }
                list.clear();
                list.addAll(p);
                return;

            }else if(opcion.equals("Cedula")){
                query=entityManager.createNamedQuery("Presupuesto.findByCiCliente");
                query.setParameter("ciCliente", tf_valor.getText());
                 List<Presupuesto> p=query.getResultList();
                if(p.isEmpty()){
                    JOptionPane.showMessageDialog(null,"Cédula de  Cliente Inexistente!", "Error",JOptionPane.ERROR_MESSAGE);
                    tf_valor.setText(null);
                    return;
                }
                list.clear();
                list.addAll(p);
                return;
                
            }
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_buscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_buscarFocusLost
        // TODO add your handling code here:
        tf_valor.setText(null);
    }//GEN-LAST:event_btn_buscarFocusLost

    private void tf_valorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_valorKeyTyped
        // TODO add your handling code here:
        String opc;
        opc=(String) list_filtros.getSelectedItem();
        if("Estado".equals(opc)){
            ch=evt.getKeyChar();
            if(Character.isDigit(ch)){
                getToolkit().beep();
                evt.consume();
            }
        }else if("Numero Presupuesto".equals(opc)){
            ch=evt.getKeyChar();
            if(!Character.isDigit(ch)){
                getToolkit().beep();
                evt.consume();
            }      
        }
    }//GEN-LAST:event_tf_valorKeyTyped

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void masterTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masterTableMouseClicked
        // TODO add your handling code here:
        switch(MenuRecepcionista.opcion){
            case 1:
                      fila=masterTable.getSelectedRow();
                      numero=(Integer) masterTable.getValueAt(fila, 0);
                      cedula=(String) masterTable.getValueAt(fila, 1);
                      estado=(String)masterTable.getValueAt(fila, 2);
                      fechaEmision=(String)masterTable.getValueAt(fila, 3);
                      JFrame frame=new ConfirmarPresupuesto();
                      ConfirmarPresupuesto.tf_numero.setText(Integer.toString(numero));
                      ConfirmarPresupuesto.tf_cedula.setText(cedula);
                      ConfirmarPresupuesto.tf_estado.setText(estado);
                      ConfirmarPresupuesto.tf_fecha.setText(fechaEmision);
                      query=entityManager.createNativeQuery("SELECT * FROM reserva r "
                      + "INNER JOIN presupuesto p "
                      + "on p.numPresupuesto = r.numPresupuesto "
                      + "WHERE r.numPresupuesto="
                      +numero, Reserva.class);
                      List<Reserva> r=query.getResultList();
                      ConfirmarPresupuesto.tf_reserva.setText(Integer.toString(r.get(0).getCodigoReserva()));
                      ConfirmarPresupuesto.tf_in.setText(formato.format(r.get(0).getCheckIn()));
                      ConfirmarPresupuesto.tf_out.setText(formato.format(r.get(0).getCheckOut()));
                      ConfirmarPresupuesto.tf_cliente.setText(r.get(0).getCodigoCliente().getNombre()+" "+
                              r.get(0).getCodigoCliente().getApellido());
                      ConfirmarPresupuesto.tf_total.setText(Integer.toString(r.get(0).getMontoTotal()));
                      frame.setVisible(true);
                      frame.setTitle("Confirmar Presupuesto");
                      frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                      frame.setLocationRelativeTo(null);
                      this.dispose();
                      break;
            case 2:
                      fila=masterTable.getSelectedRow();
                      numero=(Integer) masterTable.getValueAt(fila, 0);
                      cedula=(String) masterTable.getValueAt(fila, 1);
                      estado=(String)masterTable.getValueAt(fila, 2);
                      fechaEmision=(String)masterTable.getValueAt(fila, 3);
                      JFrame f=new EliminarPresupuesto();
                      EliminarPresupuesto.tf_numero.setText(Integer.toString(numero));
                      EliminarPresupuesto.tf_cedula.setText(cedula);
                      EliminarPresupuesto.tf_estado.setText(estado);
                      EliminarPresupuesto.tf_fecha.setText(fechaEmision);
                      query=entityManager.createNativeQuery("SELECT * FROM reserva r "
                      + "INNER JOIN presupuesto p "
                      + "on p.numPresupuesto = r.numPresupuesto "
                      + "WHERE r.numPresupuesto="
                      +numero, Reserva.class);
                      List<Reserva> re=query.getResultList();
                      EliminarPresupuesto.tf_reserva.setText(Integer.toString(re.get(0).getCodigoReserva()));
                      EliminarPresupuesto.tf_in.setText(formato.format(re.get(0).getCheckIn()));
                      EliminarPresupuesto.tf_out.setText(formato.format(re.get(0).getCheckOut()));
                      EliminarPresupuesto.tf_cliente.setText(re.get(0).getCodigoCliente().getNombre()+" "+
                              re.get(0).getCodigoCliente().getApellido());
                      EliminarPresupuesto.tf_total.setText(Integer.toString(re.get(0).getMontoTotal()));
                      f.setVisible(true);
                      f.setTitle("Eliminar Presupuesto");
                      f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                      f.setLocationRelativeTo(null);
                      this.dispose();
                        break;
            case 3:
                    break;
            
        }
    }//GEN-LAST:event_masterTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame= new BuscarPresupuesto();
                frame.setVisible(true);
                frame.setTitle("Buscar Presupuesto");
                frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                frame.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_cancelar;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_auditoria;
    private javax.swing.JLabel lbl_filtro;
    private javax.swing.JLabel lbl_valor;
    private java.util.List<bean.Presupuesto> list;
    private javax.swing.JComboBox list_filtros;
    private javax.swing.JTable masterTable;
    private javax.swing.JPanel panel_auditoria;
    private javax.persistence.Query query;
    private javax.swing.JTextField tf_valor;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
