/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import bean.DetalleCobro;
import bean.FacturaCobro;
import bean.NumberToText;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;



/**
 *
 * @author Jorge
 */
public class RegistrarDetalleCobro extends javax.swing.JFrame {
private DetalleCobro dc=new DetalleCobro();
public static String invoca;
private String letras;
private int diferencia;
private FacturaCobro f=new FacturaCobro();
private String condicion;
DateFormat form=new SimpleDateFormat("dd-MM-yyyy");
java.util.Date fecha = new Date();
    /**
     * Creates new form FormaPago
     */
    public RegistrarDetalleCobro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("proyectoPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT d FROM DetalleCobro d");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        panel_BuscarRol = new javax.swing.JPanel();
        lbl_BuscarRol = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_numero = new javax.swing.JLabel();
        tf_numero = new javax.swing.JTextField();
        list_entidad = new javax.swing.JComboBox();
        cb_cheque = new javax.swing.JCheckBox();
        lbl_entidad = new javax.swing.JLabel();
        cb_contado = new javax.swing.JCheckBox();
        cb_tc = new javax.swing.JCheckBox();
        btn_aceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_BuscarRol.setBackground(new java.awt.Color(0, 153, 255));
        panel_BuscarRol.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lbl_BuscarRol.setFont(new java.awt.Font("Corbel", 1, 30)); // NOI18N
        lbl_BuscarRol.setForeground(new java.awt.Color(255, 255, 255));
        lbl_BuscarRol.setText("Forma de Pago");

        javax.swing.GroupLayout panel_BuscarRolLayout = new javax.swing.GroupLayout(panel_BuscarRol);
        panel_BuscarRol.setLayout(panel_BuscarRolLayout);
        panel_BuscarRolLayout.setHorizontalGroup(
            panel_BuscarRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_BuscarRolLayout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addComponent(lbl_BuscarRol)
                .addGap(130, 130, 130))
        );
        panel_BuscarRolLayout.setVerticalGroup(
            panel_BuscarRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_BuscarRolLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_BuscarRol)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/formas-pago.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        lbl_numero.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        lbl_numero.setText("Número Tarjeta/Cheque:");

        tf_numero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_numeroFocusGained(evt);
            }
        });

        list_entidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cabal", "Visa", "Master Card", "American Express", "Itau", "Vision", "Continental", "BBVA", "BNF", "GNB" }));

        cb_cheque.setText("Cheque");
        cb_cheque.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cb_chequeFocusGained(evt);
            }
        });

        lbl_entidad.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        lbl_entidad.setText("Entidad:");

        cb_contado.setText("Contado");
        cb_contado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cb_contadoFocusGained(evt);
            }
        });

        cb_tc.setText("Tarjeta Crédito");
        cb_tc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cb_tcFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_numero)
                            .addComponent(lbl_entidad))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(list_entidad, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cb_contado)
                        .addGap(37, 37, 37)
                        .addComponent(cb_tc)
                        .addGap(42, 42, 42)
                        .addComponent(cb_cheque)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_contado)
                            .addComponent(cb_tc)
                            .addComponent(cb_cheque))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_numero)
                            .addComponent(tf_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_entidad)
                    .addComponent(list_entidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        btn_aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/accept.png"))); // NOI18N
        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(panel_BuscarRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(btn_aceptar)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_BuscarRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btn_aceptar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_tcFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cb_tcFocusGained
        // TODO add your handling code here:
        cb_contado.setSelected(false);
        cb_cheque.setSelected(false);
    }//GEN-LAST:event_cb_tcFocusGained

    private void cb_contadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cb_contadoFocusGained
        // TODO add your handling code here:
        cb_tc.setSelected(false);
        cb_cheque.setSelected(false);
    }//GEN-LAST:event_cb_contadoFocusGained

    private void cb_chequeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cb_chequeFocusGained
        // TODO add your handling code here:
         cb_tc.setSelected(false);
          cb_contado.setSelected(false);
    }//GEN-LAST:event_cb_chequeFocusGained

    private void tf_numeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_numeroFocusGained
        // TODO add your handling code here:
     
    }//GEN-LAST:event_tf_numeroFocusGained

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        // TODO add your handling code here:
       if(cb_tc.isSelected()){
           if(tf_numero.getText().length()==0){
                JOptionPane.showMessageDialog(null,"No se ha ingresado el numero de Tarjeta", "Error",JOptionPane.ERROR_MESSAGE);
           }else{
                dc.setEntidad((String) list_entidad.getSelectedItem());
                dc.setNumeroChTarj(tf_numero.getText());
                dc.setForma("Tarjeta Crédito");
                entityManager.getTransaction().begin();
                entityManager.persist(dc);
           }
           
       }
       if(cb_cheque.isSelected()){
           if(tf_numero.getText().length()==0){
                JOptionPane.showMessageDialog(null,"No se ha ingresado el numero de Cheque", "Error",JOptionPane.ERROR_MESSAGE);
           }else{
               
                dc.setEntidad((String) list_entidad.getSelectedItem());
                dc.setNumeroChTarj(tf_numero.getText());
                dc.setForma("Cheque");
                entityManager.getTransaction().begin();
                entityManager.persist(dc);
           }
           
       }
       if(cb_contado.isSelected()){
                dc.setForma("Contado");
                entityManager.getTransaction().begin();
                entityManager.persist(dc);
           
      
       }
       this.dispose();
       if("Crear Reserva".equals(invoca)){
           generarFactCrearReserva();
           
       }
       if("Editar Reserva".equals(invoca)){
           generarFactEditarReserva();
       }
    }//GEN-LAST:event_btn_aceptarActionPerformed
private void   generarFactCrearReserva(){
    f.setCodigoReserva(CrearReserva.reserva);
           f.setConcepto("anticipo de reserva");
           if("".equals(CrearReserva.reserva.getCodigoCliente().getRuc())){
                  f.setRucCliente(CrearReserva.reserva.getCodigoCliente().getCedula());
           }else{
                   f.setRucCliente(CrearReserva.reserva.getCodigoCliente().getRuc());
                 }
              f.setFechaEmision(form.format(fecha));
              f.setTotal(Integer.parseInt(Integer.toString(CrearReserva.reserva.getMontoAbonado())));
             
               if("Cheque".equals(dc.getForma()) || "Tarjeta Crédito".equals(dc.getForma()) ){
                     condicion="Crédito";
                                 
               }else{
                      condicion="Contado";
               } 
              f.setFormaPago(dc);
               f.setTipoFactura(condicion);
              entityManager.persist(f);
              entityManager.flush();
              entityManager.getTransaction().commit();
             //verificar la condicion de pago
               try
                  {
                      NumberToText nt=new NumberToText();
                      letras=nt.convertirLetras(f.getTotal());
                      diferencia=CrearReserva.reserva.getMontoTotal()-CrearReserva.reserva.getMontoAbonado();
                      System.out.print(letras);
                      Class.forName("com.mysql.jdbc.Driver");
                      Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel db", "root", "user");
                       HashMap par = new HashMap();//no definimos ningún parámetro por eso lo dejamos así
                       Map parametros=new HashMap();
                       System.out.print(f.getNumFactura());
                       par.put("Letras", letras);
                       par.put("NumFactura",f.getNumFactura() );
                       par.put("Saldo",diferencia);
                       par.put("Condicion", condicion);
                       JasperPrint jp = JasperFillManager.fillReport("C:/Proyecto-II/src/reportes/facturaAnticipo.jasper", par,con);//el primer parámetro es el camino del archivo, se cambia esta dirección por la dirección del archivo .jasper
                       JasperViewer jv = new JasperViewer(jp,false);
                       jv.setVisible(true);
                       jv.setTitle("Factura de Anticipio de Reserva");
                       Image icon = new ImageIcon(getClass().getResource("/imagenes/hotel2.png")).getImage();
                       jv.setIconImage(icon);
                       jv.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    }
                       catch(Exception e)
                       {
                          e.printStackTrace();
                        }
}
private void   generarFactEditarReserva(){
      f.setCodigoReserva(ReservaEditar.reservaLocal);
      f.setConcepto("anticipo de reserva");
      if("".equals(ReservaEditar.reservaLocal.getCodigoCliente().getRuc())){
                  f.setRucCliente(ReservaEditar.reservaLocal.getCodigoCliente().getCedula());
     }else{
                  f.setRucCliente(ReservaEditar.reservaLocal.getCodigoCliente().getRuc());
      }
    f.setFechaEmision(form.format(fecha));
    f.setTotal(ReservaEditar.monto_fac);
    if("Cheque".equals(dc.getForma()) || "Tarjeta Crédito".equals(dc.getForma()) ){
                     condicion="Crédito";

   }else{
                     condicion="Contado";
   }
    f.setTipoFactura(condicion);
    f.setFormaPago(dc);
    entityManager.persist(f);
    entityManager.flush();
    entityManager.getTransaction().commit();
     try
      {
        //convertimos el numero en letras
        NumberToText nt=new NumberToText();
        letras=nt.convertirLetras(f.getTotal());
        System.out.print(letras);
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel db", "root", "user");
        HashMap par = new HashMap();//no definimos ningún parámetro por eso lo dejamos así
        Map parametros=new HashMap();
        System.out.print(f.getNumFactura());
        par.put("Letras", letras);
        par.put("NumFactura",f.getNumFactura() );
        par.put("Saldo", diferencia);
        par.put("Condicion", condicion);
        JasperPrint jp = JasperFillManager.fillReport("C:/Proyecto-II/src/reportes/facturaAnticipo.jasper", par,con);//el primer parámetro es el camino del archivo, se cambia esta dirección por la dirección del archivo .jasper
        JasperViewer jv = new JasperViewer(jp,false);
        jv.setVisible(true);
        jv.setTitle("Factura de Anticipo de Reserva");
        Image icon = new ImageIcon(getClass().getResource("/imagenes/hotel2.png")).getImage();
        jv.setIconImage(icon);
        jv.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
     }
        catch(Exception e)
     {
        e.printStackTrace();
     }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String  args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarDetalleCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarDetalleCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarDetalleCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarDetalleCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame=new RegistrarDetalleCobro();
                frame.pack();
                frame.setVisible(true);
                Image icon = new ImageIcon(getClass().getResource("/imagenes/hotel2.png")).getImage();
                frame.setIconImage(icon);
                frame.setTitle("Forma de Pago");
                frame.setLocationRelativeTo(null);
                frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cb_cheque;
    private javax.swing.JCheckBox cb_contado;
    private javax.swing.JCheckBox cb_tc;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_BuscarRol;
    private javax.swing.JLabel lbl_entidad;
    private javax.swing.JLabel lbl_numero;
    private java.util.List<DetalleCobro> list;
    private javax.swing.JComboBox list_entidad;
    private javax.swing.JPanel panel_BuscarRol;
    private javax.persistence.Query query;
    private javax.swing.JTextField tf_numero;
    // End of variables declaration//GEN-END:variables
}
