/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ViewAdmHotel;

import bean.Asistencia;
import bean.AuditoriaSistema;
import bean.Eventos;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorge
 */
public class EliminarAsistencia extends javax.swing.JFrame {
    public static Asistencia asistencia;
    private int resp;
     DateFormat format=new SimpleDateFormat("yyyy-MM-dd");

    /**
     * Creates new form EliminarAsistencia
     */
    public EliminarAsistencia() {
        initComponents();
        inicializarAsistencia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_EditarLugar = new javax.swing.JPanel();
        lbl_EditarLugar = new javax.swing.JLabel();
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("proyectoPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT a FROM Asistencia a");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        panel_EditarLugar1 = new javax.swing.JPanel();
        lbl_EditarLugar1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_horaSalida = new javax.swing.JLabel();
        tf_codEmpleado = new javax.swing.JTextField();
        tf_horaSalida = new javax.swing.JTextField();
        lbl_fechaAsist = new javax.swing.JLabel();
        tf_datosEmp = new javax.swing.JTextField();
        lbl_horaEntrada = new javax.swing.JLabel();
        lbl_codEmpleado = new javax.swing.JLabel();
        tf_horasT = new javax.swing.JTextField();
        tf_horaEntrada = new javax.swing.JTextField();
        lbl_horasT = new javax.swing.JLabel();
        tf_fechaAsist = new javax.swing.JTextField();
        lbl_codAsistencia = new javax.swing.JLabel();
        tf_codAsistencia = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btn_cancelar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();

        panel_EditarLugar.setBackground(new java.awt.Color(0, 153, 255));
        panel_EditarLugar.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lbl_EditarLugar.setFont(new java.awt.Font("Corbel", 1, 26)); // NOI18N
        lbl_EditarLugar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_EditarLugar.setText("Eliminar Seguimiento de Actividad");

        javax.swing.GroupLayout panel_EditarLugarLayout = new javax.swing.GroupLayout(panel_EditarLugar);
        panel_EditarLugar.setLayout(panel_EditarLugarLayout);
        panel_EditarLugarLayout.setHorizontalGroup(
            panel_EditarLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_EditarLugarLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lbl_EditarLugar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_EditarLugarLayout.setVerticalGroup(
            panel_EditarLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_EditarLugarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_EditarLugar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_EditarLugar1.setBackground(new java.awt.Color(0, 153, 255));
        panel_EditarLugar1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lbl_EditarLugar1.setFont(new java.awt.Font("Corbel", 1, 26)); // NOI18N
        lbl_EditarLugar1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_EditarLugar1.setText("Eliminar Asistencia");

        javax.swing.GroupLayout panel_EditarLugar1Layout = new javax.swing.GroupLayout(panel_EditarLugar1);
        panel_EditarLugar1.setLayout(panel_EditarLugar1Layout);
        panel_EditarLugar1Layout.setHorizontalGroup(
            panel_EditarLugar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_EditarLugar1Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(lbl_EditarLugar1)
                .addContainerGap(237, Short.MAX_VALUE))
        );
        panel_EditarLugar1Layout.setVerticalGroup(
            panel_EditarLugar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_EditarLugar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_EditarLugar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_horaSalida.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        lbl_horaSalida.setText("Hora Salida:");

        tf_codEmpleado.setEnabled(false);
        tf_codEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_codEmpleadoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_codEmpleadoKeyTyped(evt);
            }
        });

        tf_horaSalida.setEnabled(false);

        lbl_fechaAsist.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        lbl_fechaAsist.setText("Fecha Asistencia:");

        tf_datosEmp.setEnabled(false);

        lbl_horaEntrada.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        lbl_horaEntrada.setText("Hora Entrada:");

        lbl_codEmpleado.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        lbl_codEmpleado.setText("Empleado:");

        tf_horasT.setEnabled(false);

        tf_horaEntrada.setEnabled(false);

        lbl_horasT.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        lbl_horasT.setText("Horas Trabajadas:");

        tf_fechaAsist.setEnabled(false);

        lbl_codAsistencia.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        lbl_codAsistencia.setText("Código Asistencia:");

        tf_codAsistencia.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_codAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(lbl_horaEntrada)
                                .addGap(18, 18, 18)
                                .addComponent(tf_horaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_horaSalida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_horaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(lbl_horasT)
                        .addGap(18, 18, 18)
                        .addComponent(tf_horasT, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(262, 262, 262)
                                .addComponent(lbl_fechaAsist)
                                .addGap(29, 29, 29)
                                .addComponent(tf_fechaAsist, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_codAsistencia)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lbl_codEmpleado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_codEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tf_datosEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_codEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_codEmpleado)
                    .addComponent(tf_datosEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_fechaAsist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_fechaAsist)
                    .addComponent(lbl_codAsistencia)
                    .addComponent(tf_codAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_horasT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_horasT)
                    .addComponent(lbl_horaSalida)
                    .addComponent(tf_horaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_horaEntrada)
                    .addComponent(tf_horaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete.png"))); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trash.png"))); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_eliminar)
                .addGap(48, 48, 48)
                .addComponent(btn_cancelar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_eliminar)
                    .addComponent(btn_cancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_EditarLugar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(panel_EditarLugar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_codEmpleadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_codEmpleadoKeyPressed
        // TODO add your handling code here:
  
    }//GEN-LAST:event_tf_codEmpleadoKeyPressed

    private void tf_codEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_codEmpleadoKeyTyped
        // TODO add your handling code here:
 
    }//GEN-LAST:event_tf_codEmpleadoKeyTyped

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
        int cod;
        String valor;
        cod=Integer.parseInt(tf_codEmpleado.getText());
        JOptionPane.showMessageDialog(null, "Existen registros de eventos para esta asistencia,"
                    + "si elimina perderá dichos registros","Aviso",JOptionPane.INFORMATION_MESSAGE );
            resp=  JOptionPane.showConfirmDialog(null,"Esta seguro que desea eliminar?", "Confirmar Eliminación",JOptionPane.YES_NO_OPTION );
            if (resp==JOptionPane.YES_OPTION){
                entityManager.getTransaction().begin();
                query=entityManager.createNativeQuery("SELECT * FROM eventos WHERE "
                        + "codigoEmpleado= "
                        +cod+" AND fecha_inicio="+"'"+tf_fechaAsist.getText()+"'",Eventos.class);
                List<Eventos> e=query.getResultList();
                if(e.size()>=1){
                    for(int i=0;i<e.size();i++){
                        entityManager.remove(e.get(i));
                    }
                    entityManager.flush();
                }
                Asistencia a=entityManager.find(Asistencia.class,Integer.parseInt(tf_codAsistencia.getText()));
                valor=a.toString();//guardamos el objeto antes de eliminar
                entityManager.remove(a);
                AuditoriaSistema as=new AuditoriaSistema();
                as.setAccion("Eliminación");
                as.setTabla("Asistencia");
                Date fecha=new Date();
                DateFormat formato=new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
                as.setFechaHora(formato.format(fecha));
                as.setUsuario("nadie");
                as.setAntes(valor);
                as.setDespues("No hay modificaciones");
                entityManager.persist(as);
                entityManager.getTransaction().commit();
                entityManager.close();
                JOptionPane.showMessageDialog(null, "Eliminación Exitosa");
            }
            this.dispose();
    }//GEN-LAST:event_btn_eliminarActionPerformed
    private void inicializarAsistencia(){
        tf_codEmpleado.setText(Integer.toString(asistencia.getCodigoEmpleado().getCodigoEmpleado()));
        tf_datosEmp.setText(asistencia.getCodigoEmpleado().getNombre()+" "+asistencia.getCodigoEmpleado().getApellido());
       tf_fechaAsist.setText(format.format(asistencia.getFechaAsistencia()));
       tf_horaEntrada.setText(asistencia.getHoraEntrada());
       tf_horaSalida.setText(asistencia.getHoraSalida());
       tf_horasT.setText(asistencia.getHorasTrabajadas().toString());
       tf_codAsistencia.setText(Integer.toString(asistencia.getCodigoAsistencia()));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame=new BuscarAsistencia();
                frame.setVisible(true);
                frame.setTitle("Buscar Asistencia");
                frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                frame.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_eliminar;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_EditarLugar;
    private javax.swing.JLabel lbl_EditarLugar1;
    private javax.swing.JLabel lbl_codAsistencia;
    private javax.swing.JLabel lbl_codEmpleado;
    private javax.swing.JLabel lbl_fechaAsist;
    private javax.swing.JLabel lbl_horaEntrada;
    private javax.swing.JLabel lbl_horaSalida;
    private javax.swing.JLabel lbl_horasT;
    private java.util.List<bean.Asistencia> list;
    private javax.swing.JPanel panel_EditarLugar;
    private javax.swing.JPanel panel_EditarLugar1;
    private javax.persistence.Query query;
    private javax.swing.JTextField tf_codAsistencia;
    public static javax.swing.JTextField tf_codEmpleado;
    public static javax.swing.JTextField tf_datosEmp;
    public static javax.swing.JTextField tf_fechaAsist;
    public static javax.swing.JTextField tf_horaEntrada;
    public static javax.swing.JTextField tf_horaSalida;
    public static javax.swing.JTextField tf_horasT;
    // End of variables declaration//GEN-END:variables
}
