/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ViewAdmHotel;

import bean.Asistencia;
import bean.Empleado;
import bean.Eventos;
import bean.data;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorge
 */
public class RegistrarAsistencia extends javax.swing.JFrame {

   String horaE;
   String horaS; 
   String fecha2;
   float difH;
     float difM;
     float div;
     float horasT;
     String hs;
 SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
 SimpleDateFormat formatoHora = new SimpleDateFormat("HH:mm");
  List<Asistencia> as;
    /**
     * Creates new form RAsistencia
     */
    data mostrar_datos;
    public RegistrarAsistencia() {
        initComponents();
        mostrar_datos = new data();
        mostrar_datos.el_dato();//primero tengo que ejecutar este metodo para después ejecutar el resto
        lbl_fecha.setText(mostrar_datos.dia_semana+ " "+mostrar_datos.dia+" de "+mostrar_datos.mes+" del año "+mostrar_datos.anho);
        timer1.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("proyectoPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT a FROM Asistencia a");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        panel_regActividad = new javax.swing.JPanel();
        lbl_registrarActividad = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_tres = new javax.swing.JButton();
        btn_ocho = new javax.swing.JButton();
        btn_cuatro = new javax.swing.JButton();
        btn_cinco = new javax.swing.JButton();
        btn_uno = new javax.swing.JButton();
        btn_dos = new javax.swing.JButton();
        btn_siete = new javax.swing.JButton();
        btn_seis = new javax.swing.JButton();
        btn_nueve = new javax.swing.JButton();
        btn_cero = new javax.swing.JButton();
        btn_borrar = new javax.swing.JButton();
        btn_aceptar = new javax.swing.JButton();
        tf_codigoEmpleado = new javax.swing.JTextField();
        lbl_fecha = new javax.swing.JLabel();
        lbl_hora = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_salida2 = new javax.swing.JLabel();
        lbl_salida = new javax.swing.JLabel();
        lbl_entrada = new javax.swing.JLabel();
        lbl_entrada2 = new javax.swing.JLabel();
        lbl_empleado = new javax.swing.JLabel();

        timer1.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer1OnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_regActividad.setBackground(new java.awt.Color(0, 153, 255));
        panel_regActividad.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lbl_registrarActividad.setFont(new java.awt.Font("Corbel", 1, 30)); // NOI18N
        lbl_registrarActividad.setForeground(new java.awt.Color(255, 255, 255));
        lbl_registrarActividad.setText("Registrar Asistencia");

        javax.swing.GroupLayout panel_regActividadLayout = new javax.swing.GroupLayout(panel_regActividad);
        panel_regActividad.setLayout(panel_regActividadLayout);
        panel_regActividadLayout.setHorizontalGroup(
            panel_regActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_regActividadLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lbl_registrarActividad)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        panel_regActividadLayout.setVerticalGroup(
            panel_regActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_regActividadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_registrarActividad)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_tres.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_tres.setForeground(new java.awt.Color(0, 153, 255));
        btn_tres.setText("3");
        btn_tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tresActionPerformed(evt);
            }
        });

        btn_ocho.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_ocho.setForeground(new java.awt.Color(0, 153, 255));
        btn_ocho.setText("8");
        btn_ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ochoActionPerformed(evt);
            }
        });

        btn_cuatro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_cuatro.setForeground(new java.awt.Color(0, 153, 255));
        btn_cuatro.setText("4");
        btn_cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cuatroActionPerformed(evt);
            }
        });

        btn_cinco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_cinco.setForeground(new java.awt.Color(0, 153, 255));
        btn_cinco.setText("5");
        btn_cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cincoActionPerformed(evt);
            }
        });

        btn_uno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_uno.setForeground(new java.awt.Color(0, 153, 255));
        btn_uno.setText("1");
        btn_uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_unoActionPerformed(evt);
            }
        });

        btn_dos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_dos.setForeground(new java.awt.Color(0, 153, 255));
        btn_dos.setText("2");
        btn_dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dosActionPerformed(evt);
            }
        });

        btn_siete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_siete.setForeground(new java.awt.Color(0, 153, 255));
        btn_siete.setText("7");
        btn_siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sieteActionPerformed(evt);
            }
        });

        btn_seis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_seis.setForeground(new java.awt.Color(0, 153, 255));
        btn_seis.setText("6");
        btn_seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seisActionPerformed(evt);
            }
        });

        btn_nueve.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_nueve.setForeground(new java.awt.Color(0, 153, 255));
        btn_nueve.setText("9");
        btn_nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nueveActionPerformed(evt);
            }
        });

        btn_cero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_cero.setForeground(new java.awt.Color(0, 153, 255));
        btn_cero.setText("0");
        btn_cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ceroActionPerformed(evt);
            }
        });

        btn_borrar.setText("Borrar");
        btn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarActionPerformed(evt);
            }
        });

        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_borrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_cuatro)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cinco)
                        .addGap(18, 18, 18)
                        .addComponent(btn_seis))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_uno)
                        .addGap(18, 18, 18)
                        .addComponent(btn_dos)
                        .addGap(18, 18, 18)
                        .addComponent(btn_tres))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_siete)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_cero)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_ocho)
                                .addGap(18, 18, 18)
                                .addComponent(btn_nueve)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aceptar)
                    .addComponent(btn_borrar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_uno)
                    .addComponent(btn_dos)
                    .addComponent(btn_tres))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_seis)
                    .addComponent(btn_cinco)
                    .addComponent(btn_cuatro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ocho)
                    .addComponent(btn_siete)
                    .addComponent(btn_nueve))
                .addGap(18, 18, 18)
                .addComponent(btn_cero)
                .addContainerGap())
        );

        tf_codigoEmpleado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lbl_fecha.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        lbl_fecha.setForeground(new java.awt.Color(0, 153, 255));
        lbl_fecha.setText("jLabel1");

        lbl_hora.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        lbl_hora.setForeground(new java.awt.Color(0, 153, 255));
        lbl_hora.setText("jLabel1");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_salida2.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N

        lbl_salida.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        lbl_salida.setText("Hora Salida:");

        lbl_entrada.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        lbl_entrada.setText("Hora Entrada:");

        lbl_entrada2.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N

        lbl_empleado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_entrada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_entrada2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_salida)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_salida2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(lbl_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_entrada)
                    .addComponent(lbl_entrada2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_salida, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_salida2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panel_regActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(tf_codigoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(panel_regActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(lbl_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tf_codigoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_unoActionPerformed
        // TODO add your handling code here:
        String cadena;
        if(tf_codigoEmpleado.getText().length()==0){
            tf_codigoEmpleado.setText("1");
        }
        else{
            cadena=tf_codigoEmpleado.getText()+"1";
             tf_codigoEmpleado.setText(cadena);
        }
    }//GEN-LAST:event_btn_unoActionPerformed

    private void btn_dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dosActionPerformed
        // TODO add your handling code here:
        String cadena;
        if(tf_codigoEmpleado.getText().length()==0){
            tf_codigoEmpleado.setText("2");
        }
        else{
            cadena=tf_codigoEmpleado.getText()+"2";
            tf_codigoEmpleado.setText(cadena);
        }
         
        
    }//GEN-LAST:event_btn_dosActionPerformed

    private void btn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarActionPerformed
        // TODO add your handling code here:
        tf_codigoEmpleado.setText(null);
    }//GEN-LAST:event_btn_borrarActionPerformed

    private void btn_tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tresActionPerformed
        // TODO add your handling code here:
         String cadena;
        if(tf_codigoEmpleado.getText().length()==0){
            tf_codigoEmpleado.setText("3");
        }
        else{
            cadena=tf_codigoEmpleado.getText()+"3";
            tf_codigoEmpleado.setText(cadena);
        }
    }//GEN-LAST:event_btn_tresActionPerformed

    private void btn_cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cuatroActionPerformed
        // TODO add your handling code here:
         String cadena;
        if(tf_codigoEmpleado.getText().length()==0){
            tf_codigoEmpleado.setText("4");
        }
        else{
            cadena=tf_codigoEmpleado.getText()+"4";
            tf_codigoEmpleado.setText(cadena);
        }
    }//GEN-LAST:event_btn_cuatroActionPerformed

    private void btn_cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cincoActionPerformed
        // TODO add your handling code here:
         String cadena;
        if(tf_codigoEmpleado.getText().length()==0){
            tf_codigoEmpleado.setText("5");
        }
        else{
            cadena=tf_codigoEmpleado.getText()+"5";
            tf_codigoEmpleado.setText(cadena);
        }
    }//GEN-LAST:event_btn_cincoActionPerformed

    private void btn_seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seisActionPerformed
        // TODO add your handling code here:
         String cadena;
        if(tf_codigoEmpleado.getText().length()==0){
            tf_codigoEmpleado.setText("6");
        }
        else{
            cadena=tf_codigoEmpleado.getText()+"6";
            tf_codigoEmpleado.setText(cadena);
        }
    }//GEN-LAST:event_btn_seisActionPerformed

    private void btn_sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sieteActionPerformed
        // TODO add your handling code here:
         String cadena;
        if(tf_codigoEmpleado.getText().length()==0){
            tf_codigoEmpleado.setText("7");
        }
        else{
            cadena=tf_codigoEmpleado.getText()+"7";
            tf_codigoEmpleado.setText(cadena);
        }
    }//GEN-LAST:event_btn_sieteActionPerformed

    private void btn_ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ochoActionPerformed
        // TODO add your handling code here:
         String cadena;
        if(tf_codigoEmpleado.getText().length()==0){
            tf_codigoEmpleado.setText("8");
        }
        else{
            cadena=tf_codigoEmpleado.getText()+"8";
            tf_codigoEmpleado.setText(cadena);
        }
    }//GEN-LAST:event_btn_ochoActionPerformed

    private void btn_nueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nueveActionPerformed
        // TODO add your handling code here:
         String cadena;
        if(tf_codigoEmpleado.getText().length()==0){
            tf_codigoEmpleado.setText("9");
        }
        else{
            cadena=tf_codigoEmpleado.getText()+"9";
            tf_codigoEmpleado.setText(cadena);
        }
    }//GEN-LAST:event_btn_nueveActionPerformed

    private void btn_ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ceroActionPerformed
        // TODO add your handling code here:
         String cadena;
        if(tf_codigoEmpleado.getText().length()==0){
            tf_codigoEmpleado.setText("0");
        }
        else{
            cadena=tf_codigoEmpleado.getText()+"0";
            tf_codigoEmpleado.setText(cadena);
        }
    }//GEN-LAST:event_btn_ceroActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        // TODO add your handling code here:
        int id;
        Date fecha=new Date();
        if(tf_codigoEmpleado.getText().length()==0){
            JOptionPane.showMessageDialog(null,"Ingrese su código de empleado", "Error",JOptionPane.ERROR_MESSAGE);
            tf_codigoEmpleado.setText(null);
            return;
        }
        id=Integer.parseInt(tf_codigoEmpleado.getText());
        query=entityManager.createNamedQuery("Empleado.findByCodigoEmpleado");
        query.setParameter("codigoEmpleado", id);
        List <Empleado> e=query.getResultList();
        if(e.isEmpty()){
                JOptionPane.showMessageDialog(null,"Empleado Inexistente", "Error",JOptionPane.ERROR_MESSAGE);
                tf_codigoEmpleado.setText(null);
                     
         }
          else{
                  fecha2=formato.format(fecha);
                //verificar si el empleado está suspendido
                query=entityManager.createNativeQuery("SELECT * FROM eventos WHERE codigoEmpleado= "+id
                    +" AND ('"+fecha2+"' >=fecha_inicio AND "
                    +"'"+fecha2+"' <=fecha_fin )", Eventos.class);
                List<Eventos> ev=query.getResultList();
                if(ev.size()>=1){
                    JOptionPane.showMessageDialog(null,"Empleado suspendido, no puede marcar asistencia", "Error",JOptionPane.ERROR_MESSAGE);
                }else{
                        // verificamos si ya marcó entrada
                         query=entityManager.createNativeQuery("SELECT * FROM asistencia WHERE codigoEmpleado= "+id
                        + " AND fechaAsistencia= "
                        +"'"+fecha2+"'", Asistencia.class);
                         as=query.getResultList();
                         if(!as.isEmpty()){ //ya marco la entrada o marco entrada y salida
                                 if(as.get(0).getHoraSalida()==null){
                                     lbl_empleado.setText(e.get(0).getNombre().toUpperCase()+" "+e.get(0).getApellido().toUpperCase());
                                    // lbl_entrada2.setText(formatoHora.format(as.get(0).getHoraEntrada()));
                                     horaE=as.get(0).getHoraEntrada();
                                     lbl_entrada2.setText(horaE);
                                     horaS=formatoHora.format(fecha);
                                     lbl_salida2.setText(horaS);
                                     entityManager.getTransaction().begin();
                                     Asistencia asis= new Asistencia();
                                     asis.setCodigoAsistencia(as.get(0).getCodigoAsistencia());
                                     asis.setCodigoEmpleado(as.get(0).getCodigoEmpleado());
                                     asis.setFechaAsistencia(as.get(0).getFechaAsistencia());
                                     asis.setHoraEntrada(as.get(0).getHoraEntrada());
                                  /*   try {
                                      //  asis.setHoraSalida(horaS);
                                     } catch (ParseException ex) {
                                         Logger.getLogger(RegistrarAsistencia.class.getName()).log(Level.SEVERE, null, ex);
                                     }*/
                                     asis.setHoraSalida(horaS);
                                     asis.setHorasTrabajadas(horasTrabajadas());
                                     entityManager.merge(asis);
                                     entityManager.getTransaction().commit();
                                     JOptionPane.showMessageDialog(null,"Registro de Salida Exitoso", "Confirmación",JOptionPane.INFORMATION_MESSAGE);
                                }else{ //ya marco la entrada y salida
                                    JOptionPane.showMessageDialog(null,"Ya se ha marcado la entrada y salida en la fecha", "Aviso",JOptionPane.INFORMATION_MESSAGE);
                                }
                         }else{ //todavia no marcó entrada
                             lbl_empleado.setText(e.get(0).getNombre().toUpperCase()+" "+e.get(0).getApellido().toUpperCase());
                             horaE=formatoHora.format(fecha);
                             lbl_entrada2.setText(horaE);
                             Asistencia a=new Asistencia();
                             a.setCodigoEmpleado(e.get(0));
                             try {
                                 a.setFechaAsistencia(formato.parse(formato.format(fecha)));
                                 a.setHoraEntrada(horaE);
                             } catch (ParseException ex) {
                                Logger.getLogger(RegistrarAsistencia.class.getName()).log(Level.SEVERE, null, ex);
                             }
                             entityManager.getTransaction().begin();
                             entityManager.persist(a);
                             entityManager.getTransaction().commit();
                            JOptionPane.showMessageDialog(null,"Registro de Entrada Exitoso", "Confirmación",JOptionPane.INFORMATION_MESSAGE);
                        
                         }
                }
                //verificamos si el empleado ya marcó su entrada; si es asi se marca directo la salida
                tf_codigoEmpleado.setText(null);
                lbl_empleado.setText(null);
                lbl_entrada2.setText(null);
                lbl_salida2.setText(null);
          }
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
        // TODO add your handling code here:
        mostrar_datos.leer_hora();
        lbl_hora.setText("Hora actual: "+mostrar_datos.hora);
    }//GEN-LAST:event_timer1OnTime
public float horasTrabajadas(){
     
     DecimalFormat decimal= new DecimalFormat("0.0");
    
       try {
         
           difH=formatoHora.parse(horaS).getHours()-formatoHora.parse(horaE).getHours();
         //  difH=formatoHora.parse(horaS).getHours()-as.get(0).getHoraEntrada().getHours();
           System.out.println("Diferencia de horas"+" "+difH);
          // difM=formatoHora.parse(horaS).getMinutes()-as.get(0).getHoraEntrada().getMinutes();
            difM=formatoHora.parse(horaS).getMinutes()-formatoHora.parse(horaE).getMinutes();
           System.out.println("Diferencia de minutos"+" "+difM);
       } catch (ParseException ex) {
           Logger.getLogger(RegistrarAsistencia.class.getName()).log(Level.SEVERE, null, ex);
       }
             div=(difM/60);
             System.out.println("Division:"+" "+div);
             horasT=difH+div;
             hs =decimal.format(horasT);
             hs=hs.replaceAll(",",".");
             horasT=Float.parseFloat(hs);
             System.out.println("Total:"+" "+horasT);
             return horasT;
        
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarAsistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame frame=new RegistrarAsistencia();
                frame.setVisible(true);
                frame.setTitle("Registrar Asistencia");
                frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                frame.setLocationRelativeTo(null);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_cero;
    private javax.swing.JButton btn_cinco;
    private javax.swing.JButton btn_cuatro;
    private javax.swing.JButton btn_dos;
    private javax.swing.JButton btn_nueve;
    private javax.swing.JButton btn_ocho;
    private javax.swing.JButton btn_seis;
    private javax.swing.JButton btn_siete;
    private javax.swing.JButton btn_tres;
    private javax.swing.JButton btn_uno;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_empleado;
    private javax.swing.JLabel lbl_entrada;
    private javax.swing.JLabel lbl_entrada2;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_hora;
    private javax.swing.JLabel lbl_registrarActividad;
    private javax.swing.JLabel lbl_salida;
    private javax.swing.JLabel lbl_salida2;
    private java.util.List<bean.Asistencia> list;
    private javax.swing.JPanel panel_regActividad;
    private javax.persistence.Query query;
    private javax.swing.JTextField tf_codigoEmpleado;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    // End of variables declaration//GEN-END:variables
}
